import re
from pathlib import Path
from typing import Any

from core.common import (
    api_enabled as _api_enabled,
    codex_config_path,
    codex_root_dir,
    load_platform_config,
    toml_array,
    toml_header_key_segment,
    toml_inline_table,
    toml_quote,
    toml_section,
    toml_value,
    xcode_codex_dir,
    xcode_coding_assistant_exists,
)

MCP_BEGIN = "# BEGIN MCP SYNC (from env/mcp/)"
MCP_END = "# END MCP SYNC"
MCP_BLOCK_PATTERN = re.compile(
    r"# BEGIN MCP SYNC(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(MCP_END),
    re.DOTALL,
)

SHARED_BEGIN = "# BEGIN CODEX SHARED (from env/platforms/codex.json)"
SHARED_END = "# END CODEX SHARED"
SHARED_BLOCK_PATTERN = re.compile(
    r"# BEGIN CODEX SHARED(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(SHARED_END),
    re.DOTALL,
)


def generate_mcp_toml(servers: dict[str, Any]) -> str:
    """Generate TOML for MCP servers (platform-agnostic)."""
    lines: list[str] = ["# AUTOGENERATED from env/mcp/", ""]
    for name, raw_cfg in servers.items():
        if not isinstance(raw_cfg, dict):
            raise ValueError(f"mcpServers.{name} must be an object.")
        cfg = dict(raw_cfg)
        key = toml_header_key_segment(name)
        lines.append(f"[mcp_servers.{key}]")
        if "url" in cfg:
            lines.append(f"url = {toml_quote(str(cfg['url']))}")
            if "headers" in cfg and isinstance(cfg["headers"], dict) and cfg["headers"]:
                headers = {k: str(v) for k, v in cfg["headers"].items()}
                lines.append(f"headers = {toml_inline_table(headers)}")
        else:
            lines.append(f"command = {toml_quote(str(cfg['command']))}")
            if "args" in cfg and isinstance(cfg["args"], list):
                lines.append(f"args = {toml_array(cfg['args'])}")
        env = cfg.get("env") or {}
        if isinstance(env, dict) and env:
            values = {k: str(v) for k, v in env.items()}
            lines.append(f"env = {toml_inline_table(values)}")
        lines.append("")
    return "\n".join(lines).rstrip()


# Host-specific / per-developer keys that must NEVER be written into the managed
# CODEX SHARED block even if present in env/platforms/codex.json. Each developer
# configures these individually outside the managed block. This is a defensive
# guard: the lean team-shared config no longer lists them, but if someone re-adds
# one (e.g. a preference knob), it is skipped rather than force-synced.
_HOST_SKIP = {
    # Per-developer preference knobs (intentionally not team-shared)
    "personality",
    "model_reasoning_effort",
    "model_verbosity",
    "model_reasoning_summary",
    "plan_mode_reasoning_effort",
    "project_doc_max_bytes",
    "project_doc_fallback_filenames",
    "features",
    # Host-specific environment / UX settings
    "hide_agent_reasoning",
    "web_search",
    "file_opener",
    "history",
    "tools",
    "shell_environment_policy",
    "tui",
    "agents",
    "memories",
    "analytics",
    "feedback",
}


def generate_shared_toml(cfg: dict[str, Any], *, api_enabled: bool = True) -> str:
    """Generate Codex platform TOML from platform config.

    Uses toml_section() for automatic conversion of all team-shared settings.
    Host-specific keys (_HOST_SKIP) are excluded from the managed blocks —
    each developer configures those individually outside the blocks.

    API-owned fields (``model_provider`` / ``preferred_auth_method`` and the
    ``model_providers`` table) are gated by ``api_enabled``:

    - When enabled (default), they are emitted. An empty/unset ``model_provider``
      is still emitted as a commented placeholder (never ``model_provider =
      "None"``), so users can uncomment it later.
    - When disabled, they are **omitted entirely** (not commented out). Because
      the whole CODEX SHARED block is replaced on each sync, omission
      deterministically deletes them from the target config — matching the
      platform-sync-contract cleanup policy (prefer deletion over comments).

    ``export_env_to_zshrc`` (DATAEYES_API_KEY) is gated by the orchestrator and
    is not part of this TOML block.
    """
    lines: list[str] = ["# AUTOGENERATED from env/platforms/codex.json"]

    # ── model_provider / preferred_auth_method: API-owned, gated by api.enabled ──
    # When API sync is disabled, omit both lines so the managed block no longer
    # carries them (deterministic deletion on re-sync).
    if api_enabled:
        model_provider = cfg.get("model_provider")
        # A usable provider is a non-empty, non-blank string. None / "" / "   "
        # must be emitted as a comment (not `model_provider = "None"`), otherwise
        # Codex would try to resolve a bogus provider id.
        has_provider = isinstance(model_provider, str) and model_provider.strip() != ""
        if not has_provider:
            lines.append("# model_provider (unset in env/platforms/codex.json)")
            lines.append('# preferred_auth_method = "apikey"')
        else:
            lines.append(f"model_provider = {toml_quote(str(model_provider))}")
            lines.append('preferred_auth_method = "apikey"')

    # ── everything else via toml_section ──
    # Strip model_providers from cfg so toml_section's special handler won't
    # duplicate it.  Custom ignore must also include keys that toml_section
    # skips by default — a non-empty ignore replaces the default set entirely.
    # `api` is sync-engine metadata, not a Codex config key, so it is ignored.
    cfg_for_section = {k: v for k, v in cfg.items() if k != "model_providers"}
    section = toml_section(
        cfg_for_section,
        ignore=_HOST_SKIP
        | {"api", "model_provider", "model_providers", "env", "export_env_to_zshrc", "projects", "_comment", "preamble"},
    )
    if section.strip():
        lines.append(section)

    # ── model_providers: output after root settings; API-owned, gated ──
    providers = cfg.get("model_providers")
    if api_enabled and isinstance(providers, dict) and providers:
        for pid, pcfg in providers.items():
            if not isinstance(pcfg, dict):
                continue
            lines.extend(["", f"[model_providers.{toml_header_key_segment(str(pid))}]"])
            # Ensure `name` is present (Codex requires it)
            if "name" not in pcfg:
                lines.append(f"name = {toml_quote(str(pid))}")
            for k, v in pcfg.items():
                lines.append(f"{k} = {toml_value(v)}")

    return "\n".join(lines).rstrip()


def merge_managed_blocks(cfg_path: Path, shared_body: str, mcp_body: str) -> None:
    """Merge CODEX SHARED and MCP blocks into the target config.toml."""
    shared_block = f"{SHARED_BEGIN}\n{shared_body}\n{SHARED_END}" if shared_body else ""
    mcp_block = f"{MCP_BEGIN}\n{mcp_body}\n{MCP_END}"
    region = (shared_block + "\n\n" + mcp_block) if shared_block else mcp_block
    region = f"\n{region}\n"

    if not cfg_path.exists():
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(
            f"# Codex config\n# Add host-specific settings outside managed blocks.\n{region}",
            encoding="utf-8",
        )
        print(f"Created {cfg_path} with managed blocks.")
        return

    text = cfg_path.read_text(encoding="utf-8")
    text = SHARED_BLOCK_PATTERN.sub("", text)
    text = MCP_BLOCK_PATTERN.sub("", text)

    table_re = re.compile(r"^\[\[?[^\]\n]+\]\]?\s*$", re.MULTILINE)
    match = table_re.search(text)
    if match:
        head = text[: match.start()].rstrip()
        tail = text[match.start():]
        new_text = (head + "\n" + region + "\n" + tail) if head else (region + "\n" + tail)
        action = "Inserted managed blocks before first [table]"
    else:
        new_text = text.rstrip() + "\n" + region
        action = "Appended managed blocks"

    cfg_path.write_text(new_text, encoding="utf-8")
    print(f"{action} in {cfg_path}.")


def sync(mcp_servers: dict[str, Any], cfg: dict[str, Any]) -> None:
    """Sync MCP servers and Codex platform config to native TOML format."""
    root = codex_root_dir()
    if not root.exists():
        print(f"[codex] Codex root not found: {root} — skipping (tool not installed).")
        return

    generated = generate_mcp_toml(mcp_servers)
    shared = generate_shared_toml(cfg, api_enabled=_api_enabled(cfg))

    # Merge into config.toml
    merge_managed_blocks(codex_config_path(), shared, generated)

    # Xcode Codex target
    if not xcode_coding_assistant_exists():
        print("[codex] Xcode CodingAssistant path not found — skipping Xcode Codex sync.")
        return

    xc = xcode_codex_dir()
    xc.mkdir(parents=True, exist_ok=True)
    merge_managed_blocks(xc / "config.toml", shared, generated)
