import re
import subprocess
from pathlib import Path
from typing import Any

from .common import (
    codex_config_path,
    codex_generated_toml_path,
    env_for_platform,
    load_platform_config,
    toml_array,
    toml_header_key_segment,
    toml_inline_table,
    toml_quote,
    toml_section,
    toml_value,
    xcode_codex_dir,
)

ZSHRC_BEGIN = "# BEGIN CODEX ENV SYNC (from env/platforms/codex.json)"
ZSHRC_END = "# END CODEX ENV SYNC"
ZSHRC_BLOCK_PATTERN = re.compile(
    r"# BEGIN CODEX ENV SYNC(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(ZSHRC_END)
    + r"\n?",
    re.DOTALL,
)


def _generate_zshrc_env_block(cfg: dict[str, Any]) -> str:
    """Generate export lines for codex env vars from platform config."""
    env = env_for_platform("codex")
    if not env:
        return ""
    lines = [f'export {k}="{v}"' for k, v in env.items()]
    return "\n".join(lines)


def _sync_zshrc_env() -> None:
    """Write codex env vars into a managed block in ~/.zshrc."""
    body = _generate_zshrc_env_block({})  # cfg not needed, env_for_platform reads from file
    if not body:
        return

    block = f"{ZSHRC_BEGIN}\n{body}\n{ZSHRC_END}\n"
    zshrc = Path.home() / ".zshrc"

    if zshrc.exists():
        text = zshrc.read_text(encoding="utf-8")
        if ZSHRC_BLOCK_PATTERN.search(text):
            new_text = ZSHRC_BLOCK_PATTERN.sub(block, text)
        else:
            new_text = text.rstrip() + "\n\n" + block
    else:
        new_text = block

    zshrc.write_text(new_text, encoding="utf-8")
    print(f"Updated codex env vars in {zshrc}.")

    try:
        subprocess.run(["zsh", "-c", f"source {zshrc}"], check=True, capture_output=True)
        print(f"Sourced {zshrc} (current process).")
    except subprocess.CalledProcessError as exc:
        print(f"[warn] source {zshrc} exited {exc.returncode}: {exc.stderr.decode().strip()}")


MCP_BEGIN = "# BEGIN MCP SYNC (from env/mcp/)"
MCP_END = "# END MCP SYNC"
MCP_BLOCK_PATTERN = re.compile(
    r"# BEGIN MCP SYNC(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(MCP_END),
    re.DOTALL,
)

SHARED_BEGIN = "# BEGIN CODEX SHARED (from env/platforms/codex.json)"
SHARED_END = "# END CODEX SHARED"
SHARED_BLOCK_PATTERN = re.compile(
    r"# BEGIN CODEX SHARED(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(SHARED_END),
    re.DOTALL,
)


def generate_mcp_toml(servers: dict[str, Any]) -> str:
    """Generate TOML for MCP servers (platform-agnostic)."""
    lines: list[str] = ["# AUTOGENERATED from env/mcp/", ""]
    for name, raw_cfg in servers.items():
        if not isinstance(raw_cfg, dict):
            raise ValueError(f"mcpServers.{name} must be an object.")
        cfg = dict(raw_cfg)
        key = toml_header_key_segment(name)
        lines.append(f"[mcp_servers.{key}]")
        if "url" in cfg:
            lines.append(f"url = {toml_quote(str(cfg['url']))}")
            if "headers" in cfg and isinstance(cfg["headers"], dict) and cfg["headers"]:
                headers = {k: str(v) for k, v in cfg["headers"].items()}
                lines.append(f"headers = {toml_inline_table(headers)}")
        else:
            lines.append(f"command = {toml_quote(str(cfg['command']))}")
            if "args" in cfg and isinstance(cfg["args"], list):
                lines.append(f"args = {toml_array(cfg['args'])}")
        env = cfg.get("env") or {}
        if isinstance(env, dict) and env:
            values = {k: str(v) for k, v in env.items()}
            lines.append(f"env = {toml_inline_table(values)}")
        lines.append("")
    return "\n".join(lines).rstrip()


def generate_shared_toml(cfg: dict[str, Any]) -> str:
    """Generate Codex platform TOML from platform config.

    The platform config follows Codex's official config.toml schema,
    so we can use toml_section() for automatic conversion.
    """
    lines: list[str] = ["# AUTOGENERATED from env/platforms/codex.json"]

    # Top-level keys (model, personality, etc.)
    section = toml_section(cfg)
    if section.strip():
        lines.append(section)

    return "\n".join(lines).rstrip()


def merge_managed_blocks(cfg_path: Path, shared_body: str, mcp_body: str) -> None:
    """Merge CODEX SHARED and MCP blocks into the target config.toml."""
    shared_block = f"{SHARED_BEGIN}\n{shared_body}\n{SHARED_END}" if shared_body else ""
    mcp_block = f"{MCP_BEGIN}\n{mcp_body}\n{MCP_END}"
    region = (shared_block + "\n\n" + mcp_block) if shared_block else mcp_block
    region = f"\n{region}\n"

    if not cfg_path.exists():
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(
            f"# Codex config\n# Add host-specific settings outside managed blocks.\n{region}",
            encoding="utf-8",
        )
        print(f"Created {cfg_path} with managed blocks.")
        return

    text = cfg_path.read_text(encoding="utf-8")
    text = SHARED_BLOCK_PATTERN.sub("", text)
    text = MCP_BLOCK_PATTERN.sub("", text)

    table_re = re.compile(r"^\[\[?[^\]\n]+\]\]?\s*$", re.MULTILINE)
    match = table_re.search(text)
    if match:
        head = text[: match.start()].rstrip()
        tail = text[match.start():]
        new_text = (head + "\n" + region + "\n" + tail) if head else (region + "\n" + tail)
        action = "Inserted managed blocks before first [table]"
    else:
        new_text = text.rstrip() + "\n" + region
        action = "Appended managed blocks"

    cfg_path.write_text(new_text, encoding="utf-8")
    print(f"{action} in {cfg_path}.")


def sync(mcp_servers: dict[str, Any], cfg: dict[str, Any]) -> None:
    """Sync MCP servers and Codex platform config to native TOML format."""
    generated = generate_mcp_toml(mcp_servers)
    shared = generate_shared_toml(cfg)

    # Write standalone mcp.generated.toml
    out = codex_generated_toml_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated, encoding="utf-8")
    print(f"Wrote: {out}")

    # Merge into config.toml
    merge_managed_blocks(codex_config_path(), shared, generated)

    # Xcode Codex target
    xc = xcode_codex_dir()
    xc.mkdir(parents=True, exist_ok=True)
    xc_gen = xc / "mcp.generated.toml"
    xc_gen.write_text(generated, encoding="utf-8")
    print(f"Wrote: {xc_gen}")
    merge_managed_blocks(xc / "config.toml", shared, generated)

    # Export env vars to ~/.zshrc
    if cfg.get("env"):
        _sync_zshrc_env()
