#!/usr/bin/env python3
"""
Sync Codex configuration from this repo into:
1. $CODEX_HOME/mcp.generated.toml (or ~/.codex/mcp.generated.toml)
2. Codex user config.toml (merge into marked blocks, never overwrite other content)
3. Xcode CodingAssistant Codex dir: ~/Library/Developer/Xcode/CodingAssistant/codex/
   (same TOML + merge into that config.toml — agents launched inside Xcode only)

Two source files drive this sync:
- mcp/servers.json    → generated into the `# BEGIN/END MCP SYNC` block
- env/codex/shared.toml   → copied verbatim into the `# BEGIN/END CODEX SHARED` block
                        (fields common to CLI + Xcode: model, provider, features,
                         projects, ...)

Anything outside these two marker blocks in each target config.toml is preserved
as-is, so per-host config (developer_instructions, xcode-tools MCP, sandbox,
plugins, personality, notify, ...) stays where it belongs.

Config path resolution (first match wins):
- $CODEX_CONFIG — absolute path to config.toml
- $CODEX_HOME/config.toml — Codex default data dir (see OpenAI Codex docs)
- ~/.codex/config.toml
"""
import json
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SRC_MCP = REPO_ROOT.parent / "mcp" / "servers.json"
SRC_SHARED = REPO_ROOT.parent / "env" / "codex" / "shared.toml"


def codex_config_path() -> Path:
    if p := os.environ.get("CODEX_CONFIG"):
        return Path(p).expanduser()
    if home := os.environ.get("CODEX_HOME"):
        return Path(home).expanduser() / "config.toml"
    return Path.home() / ".codex/config.toml"


def codex_generated_toml_path() -> Path:
    if home := os.environ.get("CODEX_HOME"):
        return Path(home).expanduser() / "mcp.generated.toml"
    return Path.home() / ".codex/mcp.generated.toml"


MCP_BEGIN = "# BEGIN MCP SYNC (from mcp/servers.json)"
MCP_END = "# END MCP SYNC"
# Legacy Codex blocks used "(from servers.json)"; still match for in-place upgrade.
MCP_BLOCK_PATTERN = re.compile(
    r"# BEGIN MCP SYNC(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(MCP_END),
    re.DOTALL,
)

SHARED_BEGIN = "# BEGIN CODEX SHARED (from codex-shared.toml)"
SHARED_END = "# END CODEX SHARED"
SHARED_BLOCK_PATTERN = re.compile(
    r"# BEGIN CODEX SHARED(?: \(from [^)]+\))?"
    + r".*?"
    + re.escape(SHARED_END),
    re.DOTALL,
)


def toml_quote(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def toml_bare_key_segment(s: str) -> bool:
    """True if s is valid as an unquoted TOML key segment (letters, digits, _, -)."""
    return bool(re.fullmatch(r"[A-Za-z0-9_-]+", s))


def toml_header_key_segment(s: str) -> str:
    """Quote a table-header segment when it contains spaces, dots, or other special chars."""
    return s if toml_bare_key_segment(s) else toml_quote(s)


def toml_array(items):
    return "[" + ", ".join(toml_quote(x) for x in items) + "]"


def generate_mcp_toml(servers: dict) -> str:
    lines = []
    lines.append(f"# AUTOGENERATED from {SRC_MCP.name}")
    lines.append("")
    for name, cfg in servers.items():
        key = toml_header_key_segment(name)
        lines.append(f"[mcp_servers.{key}]")
        if "url" in cfg:
            lines.append(f"url = {toml_quote(cfg['url'])}")
        else:
            lines.append(f"command = {toml_quote(cfg['command'])}")
            if "args" in cfg:
                lines.append(f"args = {toml_array(cfg['args'])}")
        env = cfg.get("env") or {}
        if env:
            lines.append("env = { " + ", ".join(f"{k} = {toml_quote(str(v))}" for k, v in env.items()) + " }")
        lines.append("")
    return "\n".join(lines).rstrip()


def xcode_codex_dir() -> Path:
    """Codex config directory used exclusively by Xcode's built-in Coding Assistant."""
    return Path.home() / "Library/Developer/Xcode/CodingAssistant/codex"


def merge_managed_blocks(cfg: Path, shared_body: str, mcp_body: str) -> None:
    """Insert/replace both managed blocks as a single ordered region.

    Layout invariants:
      1. SHARED block comes first, then MCP block — fixed order.
      2. The whole region lives before any user-owned [table] header, so that
         SHARED's top-level scalars (model, model_provider, ...) remain top-level.
      3. Anything outside the two markers is preserved verbatim.

    A single-pass merge (rather than two independent calls) is required: the
    MCP block opens with a comment line, not a table header. If we placed
    SHARED by "first [table] header" while the MCP block already existed,
    SHARED would land inside the MCP block. Co-locating the two managed
    blocks here avoids that interleaving entirely.
    """
    shared_block = f"{SHARED_BEGIN}\n{shared_body}\n{SHARED_END}" if shared_body else ""
    mcp_block = f"{MCP_BEGIN}\n{mcp_body}\n{MCP_END}"
    region = (shared_block + "\n\n" + mcp_block) if shared_block else mcp_block
    region = f"\n{region}\n"

    if not cfg.exists():
        cfg.parent.mkdir(parents=True, exist_ok=True)
        cfg.write_text(
            f"# Codex config\n# Add your settings above; managed blocks are synced below.\n{region}",
            encoding="utf-8",
        )
        print(f"Created {cfg} with managed blocks.")
        return

    text = cfg.read_text(encoding="utf-8")
    text = SHARED_BLOCK_PATTERN.sub("", text)
    text = MCP_BLOCK_PATTERN.sub("", text)

    table_re = re.compile(r"^\[\[?[^\]\n]+\]\]?\s*$", re.MULTILINE)
    m = table_re.search(text)
    if m:
        head = text[: m.start()].rstrip()
        tail = text[m.start():]
        new_text = (head + "\n" + region + "\n" + tail) if head else (region + "\n" + tail)
        action = "Inserted managed blocks before first [table]"
    else:
        new_text = text.rstrip() + "\n" + region
        action = "Appended managed blocks"
    cfg.write_text(new_text, encoding="utf-8")
    print(f"{action} in {cfg}.")


def main():
    if not SRC_MCP.exists():
        print(f"Skip Codex MCP sync: {SRC_MCP} not found (copy from mcp/servers.json.example).")
        return
    data = json.loads(SRC_MCP.read_text(encoding="utf-8"))
    servers = data.get("mcpServers", {})
    generated = generate_mcp_toml(servers)

    shared_body = ""
    if SRC_SHARED.exists():
        shared_body = SRC_SHARED.read_text(encoding="utf-8").rstrip()
    else:
        print(f"Skip CODEX SHARED sync: {SRC_SHARED} not found.")

    out = codex_generated_toml_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generated, encoding="utf-8")
    print(f"Wrote: {out}")

    cli_cfg = codex_config_path()
    merge_managed_blocks(cli_cfg, shared_body, generated)

    xc = xcode_codex_dir()
    xc.mkdir(parents=True, exist_ok=True)
    xc_gen = xc / "mcp.generated.toml"
    xc_gen.write_text(generated, encoding="utf-8")
    print(f"Wrote: {xc_gen}")
    xc_cfg = xc / "config.toml"
    merge_managed_blocks(xc_cfg, shared_body, generated)


if __name__ == "__main__":
    main()
